import { createRequire } from "module";
const require = createRequire(import.meta.url);

export default new Map([
  ["assert", "assert"],
  ["buffer", require.resolve("buffer")],
  ["child_process", null],
  ["cluster", null],
  ["console", "console-browserify"],
  ["constants", "constants-browserify"],
  ["crypto", "crypto-browserify"],
  ["dgram", null],
  ["dns", null],
  ["domain", "domain-browser"],
  ["events", "events"],
  ["fs", null],
  ["http", "stream-http"],
  ["https", "https-browserify"],
  ["http2", null],
  ["inspector", null],
  ["module", null],
  ["net", null],
  ["os", "os-browserify/browser.js"],
  ["path", "path-browserify"],
  ["perf_hooks", null],
  ["punycode", "punycode"],
  ["querystring", "querystring-es3"],
  ["readline", null],
  ["repl", null],
  ["stream", "stream-browserify"],
  ["_stream_duplex", "readable-stream/duplex.js"],
  ["_stream_passthrough", "readable-stream/passthrough.js"],
  ["_stream_readable", "readable-stream/readable.js"],
  ["_stream_transform", "readable-stream/transform.js"],
  ["_stream_writable", "readable-stream/writable.js"],
  ["string_decoder", "string_decoder"],
  ["sys", "util/util.js"],
  ["timers", "timers-browserify"],
  ["tls", null],
  ["tty", "tty-browserify"],
  ["url", "url"],
  ["util", "util/util.js"],
  ["vm", "vm-browserify"],
  ["zlib", "browserify-zlib"],
  ["process", require.resolve("process/browser")],
  ["_process", require.resolve("process/browser")],
]);
